name: ta_safo
description: A new application.

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path: ^1.6.2
  ## https://fontawesome.com/icons?d=gallery&m=free
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  # shared_preferences: 0.5.3+4
  package_info: ^0.4.0+6
  path_provider: ^1.1.0
  url_launcher: ^5.1.0
  ## https://pub.dev/packages/flutter_map
  # flutter_map: ^0.6.1+2
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: master
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^4.0.2
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^0.1.0+2
  # https://pub.dev/packages/firebase_performance
  firebase_performance: ^0.3.0+4
  # https://pub.dev/packages/firebase_remote_config
  firebase_remote_config: ^0.2.0+5
  # https://pub.dev/packages/flutter_pdfview
  flutter_pdfview: ^1.0.0+7
  # https://pub.dev/packages/flutter_udid
  flutter_udid: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  flutter_launcher_icons: ^0.7.2+1
  screenshots: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/