name: ta_safo
description: A new application.

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  ## https://fontawesome.com/icons?d=gallery&m=free
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  # shared_preferences: 0.5.3+4
  # package_info: ^0.4.0+5
  ## Comentado para testes com o flutter_map
  # path_provider: ^1.1.0
  # device_info: ^0.4.0+2
  ## Comentado para testes com o flutter_map
  # cached_network_image: ^1.1.0
  url_launcher: ^5.0.5
  ## https://pub.dev/packages/image_picker
  ## https://pub.dev/packages/provider
  ## https://pub.dev/packages/google_maps_flutter
  # google_maps_flutter: ^0.5.19+2
  ## https://pub.dev/packages/flutter_map
  # flutter_map: ^0.6.1+2
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: dev
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^0.0.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true
