default_platform(:android)

platform :android do
  
  desc "Run Tests"
  lane :test do
    Dir.chdir("../../") do
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh('flutter', 'build', 'appbundle')
    end
  end

  desc "Submit a new build to Internal Track on Play"
  lane :internal do
    ensure_git_branch(branch: 'master')

    ensure_git_status_clean

    Dir.chdir("../../") do
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh('flutter', 'build', 'appbundle')
    end

    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_aab: false,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_changelogs: true,
      rollout: '1.0'
    )
  end

  desc 'Promote latest release build from internal to beta on Play Store'
  lane :internal_to_beta do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'beta',
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      rollout: '1.0'
    )
  end
end
